language: cpp
os: windows

branches:
 only:
   - master

env:
  - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"

script:
  - export PATH=$MSBUILD_PATH:$PATH
  - ./genie_vs2017.bat
  - cd build
  - MSBuild.exe sdl2-tetris.vcxproj

notifications:
  email: false
  