dist: xenial
sudo: required
language: cpp
compiler: gcc

branches:
 only:
   - master

install:
  # install any dependencies required
  - sudo apt-get install libsdl2-dev -y
  - sdl2-config --version
  - sudo apt-get install libsdl2-ttf-dev -y
    
script:
  - ./genie_gmake.sh
  - cd build
  - make config=debug
  - make config=dev
  - make config=release

notifications:
  email: false
  